name: semgrep-rule-lints

on:
  pull_request:
  push:
jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: semgrep-rule-lints
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/semgrep-rule-lints
