
name: semgrep-rules-test

on: [push]

jobs:
  self_test:
    runs-on: ubuntu-latest
    name: run semgrep rules tests
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          pip install semgrep
          semgrep --test --quiet
